spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
otp:
  retry-wait-time: ${OTP_RETRY_WAIT_TIME}
  retry-count: ${OTP_RETRY_COUNT}
  time-to-live: ${OTP_TIME_TO_LIVE}

notification:
  eskiz:
    token: ${ESKIZ_TOKEN}

security:
  token:
    expiration: ${JWT_EXPIRATION}
    secretKey: ${JWT_KEY}

api:
  admin:
    password: ${ADMIN_PASSWORD}

  images:
    base:
      download-url: http://localhost:8080/attachments/download/

  storage:
    images-path: ${IMAGES_PATH}

