spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/fast_food
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  otp:
    retry-wait-time: 60
    retry-count: 3
    time-to-live: 86400
notification:
  eskiz:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTY5OTQ1NzMsImlhdCI6MTcxNDQwMjU3Mywicm9sZSI6InRlc3QiLCJzaWduIjoiMmYxMDliOTRmOWE3MWM1NjNhMGRmYWQ3NTUwYmZkOTY1ZmFkMGI4ZWQzNDQxMDFjMzE0NGJhNWQ2MzQ5YmEzOCIsInN1YiI6IjU1OTEifQ.LkOpwTRtapPhtczF4cfFtnG6c--113dKrEyIDTEuxkU

security:
  token:
    expiration: 86400
    secretKey: my-fast-food-application-secret-key
